version: '2.0'

services:
  mongodb:
    image: mongo:3.6.7-stretch
    container_name: mongo-vendas
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "vendas"
    ports:
      - 27019:27017

  mongoexpress:
    container_name: mongoexpress-vendas
    image: mongo-express:latest
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
    depends_on:
      - mongodb
